CREATE TABLE EMPLOYEE (
FNAME VARCHAR(20) NOT NULL,
MI CHAR(1),
LNAME VARCHAR(20) NOT NULL,
PHONE_NUM CHAR(12),
WORK_ID INT NOT NULL,
TITLE VARCHAR(30),
PRIMARY KEY(WORK_ID)
);

CREATE TABLE MISSION(
NAME VARCHAR(20)NOT NULL,
MISSION_ID INT NOT NULL,
MLEADER_ID INT,
ONGOING BIT,
UNIQUE(NAME),
PRIMARY KEY (MISSION_ID),
FOREIGN KEY(MLEADER_ID) REFERENCES EMPLOYEE(WORK_ID)
ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE PROJECT(
NAME VARCHAR(20) NOT NULL,
PROJ_ID INT NOT NULL,
MISSION_ID INT NOT NULL,
PLEADER_ID INT,
UNIQUE(NAME),
PRIMARY KEY (PROJ_ID),
FOREIGN KEY(MISSION_ID) REFERENCES MISSION(MISSION_ID),
FOREIGN KEY(PLEADER_ID) REFERENCES EMPLOYEE(WORK_ID)
ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE CONTRACTOR(
NAME VARCHAR(20) NOT NULL,
CONTRACTOR_ID INT NOT NULL,
PRIMARY KEY(CONTRACTOR_ID)
);

CREATE TABLE WORKS_ON(
EMPLOYEE_ID INT NOT NULL,
PROJ_ID INT,
PRIMARY KEY(EMPLOYEE_ID),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(WORK_ID),
FOREIGN KEY(PROJ_ID) REFERENCES PROJECT(PROJ_ID)
ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE SUPPLIES (
PROJ_ID INT NOT NULL,
CONTRACTOR_ID INT NOT NULL,
COST DECIMAL(18, 2),
PRIMARY KEY(PROJ_ID),
FOREIGN KEY(PROJ_ID) REFERENCES PROJECT(PROJ_ID),
FOREIGN KEY(CONTRACTOR_ID) REFERENCES CONTRACTOR(CONTRACTOR_ID)
);

